spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: adagedo
      password: adagedoDB
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 5000